apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-04T05:18:36Z"
  labels:
    run: jenkins
  name: jenkins
  namespace: testing
  resourceVersion: "3429386"
  uid: 4efc6eb0-63b0-4b3f-b226-bec00fd062e3
spec:
  securityContext:
    runAsUser: 0
  containers:
  - image: abhishekraov/jenkins_config:1.0
    imagePullPolicy: IfNotPresent
    name: jenkins
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wls6b
      readOnly: true
    - mountPath: /var/jenkins_home  # Mount path inside the container where the PVC will be mounted
      name: jenkins-data  # Name of the volume defined below
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 01hw1105382
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
      runAsUser: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-wls6b
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: jenkins-data  # Name of the volume
    persistentVolumeClaim:
      claimName: jenkins-pv-claim  # Name of your existing PVC
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-04T05:18:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-04T05:19:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-04T05:19:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-04T05:18:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6315bf157ec316c38eef2cd9d71eed0a03c3ec436e69103c5e0908c6110cc806
    image: docker.io/abhishekraov/jenkins_config:1.0
    imageID: docker.io/abhishekraov/jenkins_config@sha256:af720c47c47e6acd5c96f6882661e59dc8491006055d2a5f115911983d474d64
    lastState: {}
    name: jenkins
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-04T05:19:31Z"
  hostIP: 10.138.77.104
  phase: Running
  podIP: 10.244.0.130
  podIPs:
  - ip: 10.244.0.130
  qosClass: BestEffort
  startTime: "2024-04-04T05:18:36Z"
