apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ubuntu-webserver-small
  annotations:
    openshift.io/display-name: "Ubuntu 20.04+ VM"
    description: >-
      Template for Ubuntu 20.04 VM or newer.
      A PVC with the Ubuntu disk image must be available.
    tags: "hidden,kubevirt,virtualmachine,ubuntu"
    iconClass: "icon-ubuntu"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/kubevirt/common-templates"
    openshift.io/support-url: "https://github.com/kubevirt/common-templates/issues"
    template.openshift.io/bindable: "false"
    template.kubevirt.io/version: v1alpha1
    defaults.template.kubevirt.io/disk: rootdisk
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    name: my-ubuntu-webserver-vm
    labels:
      vm.kubevirt.io/template: ubuntu-webserver-small
      vm.kubevirt.io/template.version: "devel"
      vm.kubevirt.io/template.revision: 1
      app: my-ubuntu-webserver-vm
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.memory.guest",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1024
          }
        ]
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: my-ubuntu-webserver-vm
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
        sourceRef:
          kind: DataSource
          name: ubuntu-20.04
          namespace: kubevirt-os-images
    runStrategy: Halted
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: "ubuntu"
          vm.kubevirt.io/workload: "webserver"
          vm.kubevirt.io/flavor: "small"
        labels:
          kubevirt.io/domain: my-ubuntu-webserver-vm
          kubevirt.io/size: small
      spec:
        architecture: amd64
        domain:
          cpu:
            sockets: 1
            cores: 1
            threads: 1
          memory:
            guest: 2048
          devices:
            rng: {}
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
              model: virtio
        terminationGracePeriodSeconds: 180
        networks:
        - name: default
          pod: {}
        volumes:
        - dataVolume:
            name: my-ubuntu-webserver-vm
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: ubuntu
              password: tcs123
              chpasswd: { expire: False }
          name: cloudinitdisk
parameters:
- description: VM name
  from: 'ubuntu-[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: DATA_SOURCE_NAME
  description: Name of the DataSource to clone
  value: 'ubuntu-20.04'
- name: DATA_SOURCE_NAMESPACE
  description: Namespace of the DataSource
  value: kubevirt-os-images
- description: Randomized password for the cloud-init user ubuntu
  from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
  generate: expression
  name: CLOUD_USER_PASSWORD
